# Generated by Django 5.2.2 on 2025-07-08 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('tc', 'TC'), ('staff', 'Staff')], max_length=10, unique=True)),
                ('availed_access', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousShiftEndTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('open', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('solved', models.PositiveIntegerField(default=0)),
                ('hold', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftEndTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('open', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('solved', models.PositiveIntegerField(default=0)),
                ('hold', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('due_timestamp', models.DateTimeField(blank=True, null=True)),
                ('solved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('assigned_timestamp', models.DateTimeField(blank=True, null=True)),
                ('assignee_id', models.BigIntegerField(blank=True, null=True)),
                ('assignee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('form', models.CharField(blank=True, max_length=255, null=True)),
                ('requester_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('requester', models.CharField(blank=True, max_length=255, null=True)),
                ('product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=50, null=True)),
                ('jira_issue_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.CharField(choices=[('SH', 'SH'), ('FW DSP', 'FW DSP'), ('FW SSP', 'FW SSP'), ('Strata', 'Strata')], max_length=20)),
                ('open_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('urgent_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('normal_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('being_worked', models.IntegerField(default=0)),
                ('unattended', models.IntegerField(default=0)),
                ('engineers', models.IntegerField(default=0)),
                ('ho_followup', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('emp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('assignee_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('assignee_id', models.BigIntegerField(blank=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('work_region', models.CharField(blank=True, max_length=100, null=True)),
                ('BussinessUnit', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('repor_manager', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('tc', 'TC'), ('staff', 'Staff')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('slack_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Away', 'Away'), ('In-Meeting', 'In-Meeting'), ('Offline', 'Offline'), ('Out Of Office', 'Out Of Office')], default='Offline', max_length=20)),
                ('shift', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/image.png', null=True, upload_to='profile_images/')),
                ('access', models.JSONField(default=list)),
                ('leave_until', models.DateTimeField(blank=True, null=True)),
                ('last_shift_update', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('working_ticket', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLABreachedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('duration_of_the_breach', models.CharField(max_length=50)),
                ('reason_for_the_breach', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftEndTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('ticket_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_status', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('asignee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=100, null=True)),
                ('JIRA_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sla', models.CharField(blank=True, max_length=50, null=True)),
                ('last_comment_time', models.DateTimeField()),
                ('next_comment', models.DateTimeField()),
                ('time_left', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSLABreachedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('duration_of_the_breach', models.CharField(max_length=50)),
                ('reason_for_the_breach', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousShiftEndTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('ticket_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_status', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('asignee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=100, null=True)),
                ('JIRA_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sla', models.CharField(blank=True, max_length=50, null=True)),
                ('last_comment_time', models.DateTimeField()),
                ('next_comment', models.DateTimeField()),
                ('time_left', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('shift1_status', models.JSONField(blank=True, default=dict)),
                ('shift3_status', models.JSONField(blank=True, default=dict)),
                ('shift6_status', models.JSONField(blank=True, default=dict)),
                ('shift1_end_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift1_end_user', to='Freewheel_Portal.user')),
                ('shift3_end_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift3_end_user', to='Freewheel_Portal.user')),
                ('shift6_end_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift6_end_user', to='Freewheel_Portal.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Normal', 'Normal')], max_length=10, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.user')),
            ],
        ),
    ]
