# Generated by Django 5.2.2 on 2025-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('tc', 'TC'), ('staff', 'Staff')], max_length=10, unique=True)),
                ('availed_access', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100, unique=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('requester_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=100, null=True)),
                ('jira_issue_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assignee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(blank=True, null=True)),
                ('solved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('assigned_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('due_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('assignee_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=100)),
                ('BussinessUnit', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('repor_manager', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('tc', 'TC'), ('staff', 'Staff')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('slack_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('BRB', 'Be Right Back'), ('Meeting', 'Meeting'), ('Back', 'Back'), ('Offline', 'Offline')], default='Offline', max_length=20)),
                ('shift', models.CharField(max_length=20)),
                ('access', models.JSONField(default=list)),
            ],
        ),
    ]
