# Generated by Django 5.2.2 on 2025-07-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='synctracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
