# Generated by Django 5.2.2 on 2025-06-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Away', 'Away'), ('In-Meeting', 'In-Meeting'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
    ]
