# Generated by Django 5.2 on 2025-06-18 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0005_shiftendticketdetails_shiftendtable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Away', 'Away'), ('In-Meeting', 'In-Meeting'), ('Offline', 'Offline'), ('Out Of Office', 'Out Of Office')], default='Offline', max_length=20),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.user')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('shift1_status', models.JSONField(blank=True, default=dict)),
                ('shift3_status', models.JSONField(blank=True, default=dict)),
                ('shift1_end_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift1_end', to='Freewheel_Portal.user')),
                ('shift3_end_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift3_end', to='Freewheel_Portal.user')),
            ],
        ),
    ]
