# Generated by Django 5.2 on 2025-06-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0006_alter_user_status_notice_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shift6_end_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift6_end_user', to='Freewheel_Portal.user'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift6_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift1_end_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift1_end_user', to='Freewheel_Portal.user'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift3_end_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift3_end_user', to='Freewheel_Portal.user'),
        ),
    ]
