# Generated by Django 5.2.2 on 2025-06-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0007_schedule_shift6_end_email_schedule_shift6_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leave_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
