# Generated by Django 5.2.2 on 2025-06-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0008_user_leave_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leave_until',
        ),
    ]
