# Generated by Django 5.2.2 on 2025-06-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0010_user_leave_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leave_until',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
    ]
