# Generated by Django 5.2.2 on 2025-06-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0012_alter_user_leave_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='leave_until',
            new_name='leave_until1',
        ),
    ]
