# Generated by Django 5.2.2 on 2025-06-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0013_rename_leave_until_user_leave_until1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='leave_until1',
            new_name='leave_until',
        ),
    ]
