# Generated by Django 5.2.2 on 2025-06-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0014_rename_leave_until1_user_leave_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousShiftEndTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('open', models.PositiveIntegerField(default=0)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('solved', models.PositiveIntegerField(default=0)),
                ('hold', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousShiftEndTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('ticket_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('ticket_status', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('asignee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=100, null=True)),
                ('JIRA_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sla', models.CharField(blank=True, max_length=50, null=True)),
                ('last_comment_time', models.DateTimeField()),
                ('next_comment', models.DateTimeField()),
                ('time_left', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSLABreachedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('duration_of_the_breach', models.CharField(max_length=50)),
                ('reason_for_the_breach', models.TextField()),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.ticket')),
            ],
        ),
    ]
