# Generated by Django 5.2.2 on 2025-06-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0015_previousshiftendticketdetails_previousshiftendtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftendtable',
            name='emp_shift',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
