# Generated by Django 5.2.2 on 2025-06-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0016_shiftendtable_emp_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftendtable',
            name='emp_shift',
        ),
    ]
