# Generated by Django 5.2.2 on 2025-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0017_remove_shiftendtable_emp_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
