# Generated by Django 5.2.2 on 2025-06-20 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0018_ticket_form_ticket_group_ticket_requester'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.CharField(choices=[('SH', 'SH'), ('FW DSP', 'FW DSP'), ('FW SSP', 'FW SSP'), ('Strata', 'Strata')], max_length=20)),
                ('open_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('urgent_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('normal_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('being_worked', models.IntegerField(default=0)),
                ('unattended', models.IntegerField(default=0)),
                ('engineers', models.IntegerField(default=0)),
                ('ho_followup', models.IntegerField(default=0)),
            ],
        ),
    ]
