# Generated by Django 5.2.2 on 2025-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0019_ticketreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
