# Generated by Django 5.2.2 on 2025-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0021_user_last_shift_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/sample.png', null=True, upload_to='profile_images/'),
        ),
    ]
