# Generated by Django 5.2.2 on 2025-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0024_remove_user_last_shift_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_shift_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
