# Generated by Django 5.2.2 on 2025-06-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0025_user_last_shift_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
