# Generated by Django 5.2.2 on 2025-06-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0026_user_work_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('Normal', 'Normal')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Freewheel_Portal.user'),
        ),
    ]
