# Generated by Django 5.2.2 on 2025-06-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0027_notice_end_date_notice_priority_alter_notice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignee_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
