# Generated by Django 5.2.2 on 2025-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0028_ticket_assignee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
