# Generated by Django 5.2.2 on 2025-06-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0029_alter_ticket_assignee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
