# Generated by Django 5.2.2 on 2025-07-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0030_user_working_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='BussinessUnit',
            new_name='bussinessUnit',
        ),
    ]
