# Generated by Django 5.2.2 on 2025-07-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0031_rename_bussinessunit_user_bussinessunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bussinessUnit',
            new_name='BussinessUnit',
        ),
    ]
