# Generated by Django 5.2.4 on 2025-07-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0034_user_assignee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assignee_id',
        ),
    ]
