# Generated by Django 5.2.4 on 2025-07-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0035_remove_user_assignee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assignee_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
