# Generated by Django 5.2.4 on 2025-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freewheel_Portal', '0037_alter_user_assignee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assignee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
